const baseUrl = '/api/v1/';
export const URLS = {
    signUp: `${baseUrl}signUp`,
    signIn: `${baseUrl}signIn`,
    getLookup: `${baseUrl}getlookup/`,
    addAction: `${baseUrl}addAction`,
    getActionList: `${baseUrl}getActionList`,
    addTestcase: `${baseUrl}addTestcase`,
    getActionPagesList: `${baseUrl}getActionPagesList`,
    getActionListBypageName: `${baseUrl}getActionListBypageName`,
    inactiveAction: `${baseUrl}updateAction`,
    deleteAction: `${baseUrl}deleteAction`,
    getAbstractTestCases: `${baseUrl}getAbstractTestCases`,
    getTestcasesList: `${baseUrl}getTestcasesList`,
    getGroupsList: `${baseUrl}getGroupsList`,
    getSelectedTestCasesList: `${baseUrl}getSelectedTestCasesList`,
    selectedTestCasesUpdate: `${baseUrl}selectedTestCasesUpdate`,
    getAllTestCases: `${baseUrl}getAllTestCases`,
    createGroup: `${baseUrl}createGroup`,
    addselectedTestCases: `${baseUrl}addselectedTestCases`,
    deleteSelectTestCase: `${baseUrl}deleteSelectTestCase`,
    getGroupMappings: `${baseUrl}getGroupMappings`,
    getTestCaseByID: `${baseUrl}getTestCaseByID`,
    updateGroupMappingStatus: `${baseUrl}updateGroupMappingStatus`,
    getAllTestCaseswithoutAbstract: `${baseUrl}getAllTestCaseswithoutAbstract`,
    updateGroupStatus: `${baseUrl}updateGroupStatus`,
    getAllGroups: `${baseUrl}getAllGroups`,
    runTestCases: `${baseUrl}runTestCases`,
    getUsers: `${baseUrl}getUsers`,
    addAut: `${baseUrl}addAut`,
    getAutList: `${baseUrl}getAutList`,
    setAuth: `${baseUrl}setAuth`,
    getTestCases: `${baseUrl}getTestCases`,
    updateTestCases: `${baseUrl}updateTestCases`,
    getCurrentAction: `${baseUrl}getCurrentAction/`,
    updateAction: `${baseUrl}updateAction`,
    updatePassowrd: `${baseUrl}updatePassowrd`,
    deleteTestCase: `${baseUrl}deleteTestCase/`,
    upload: `${baseUrl}upload`,
}
export const lookupIds = {
    TYPES: 1
}
